# Numerical Evidence for log-convexity of purity as a function of loss

In [38]:
import numpy as np
from scipy.sparse import diags_array
from scipy.optimize import minimize, basinhopping

np.set_printoptions(precision=3, linewidth=200, suppress=True)

### Ladder operator definition

In [39]:
NMAX = 2

def lowering_operator(nmax=NMAX):
    return diags_array(np.sqrt(np.arange(1, nmax + 1)), offsets=1, shape=(nmax + 1, nmax +  1))

A = lowering_operator(NMAX).toarray()
ADAG = A.T

print(A)

[[0.    1.    0.   ]
 [0.    0.    1.414]
 [0.    0.    0.   ]]


### Purity formulas and derivatives

Loss equation:

\begin{equation}
    T \partial_T \rho = \left ( a^\dagger a \rho + \rho a^\dagger a \right )/2 -a \rho a^\dagger
\end{equation}

Purity definition:

\begin{equation}
    \mathcal{P}(\rho) = \mathrm{Tr}[{\rho}^2]
\end{equation}

Purity first derivative:

\begin{equation}
   T \partial_T \mathcal{P}(\rho) = 2 (\mathrm{Tr}[a^\dagger a \rho^2] - \mathrm{Tr}[a \rho a^\dagger \rho])
\end{equation}

Purity second derivative:

\begin{equation}
    T^2 {\partial_T}^2 \mathcal{P}(\rho) = 2 (
        \mathrm{Tr}[a^{\dagger 2} a^2 \rho^2]
        + 2 \mathrm{Tr}[a^\dagger a \rho a^\dagger a \rho]
        + \mathrm{Tr}[a^2 \rho a^{\dagger 2} \rho]
        - 4 \mathrm{Re} \mathrm{Tr} [\rho a^\dagger a^2 \rho a^\dagger]
    )
\end{equation}

Objective:

\begin{equation}
    \mathcal{P}(\rho) (\partial_T)^2 \log \mathcal{P}(\rho) = \mathcal{P}(\rho) (\partial_T)^2 \mathcal{P}(\rho) - (\partial_T \mathcal{P}(\rho))^2
\end{equation}

In [40]:
def purity(rho):
    return np.sum(np.conj(rho) * rho, axis=(-1, -2))


def purity_first_derivative(rho, a=A, adag=ADAG):
    return 2 * (
        np.trace(a @ rho @ rho @ adag, axis1=-1, axis2=-2) - 
        np.trace(a @ rho @ adag @ rho, axis1=-1, axis2=-2)
    )


def purity_second_derivative(rho, a=A, adag=ADAG):
    return 2 * (
        np.trace(a @ a @ rho @ adag @ adag @ rho, axis1=-1, axis2=-2) + 
        2 * np.trace((a @ rho @ adag @ a @ rho @ adag), axis1=-1, axis2=-2) +
        np.trace(a @ a @ rho @ rho @ adag @ adag, axis1=-1, axis2=-2) -
        4 * np.real(np.trace(rho @ adag @ a @ a @ rho @ adag, axis1=-1, axis2=-2))
    )


def objective(rho, a=A, adag=ADAG):
    return purity_second_derivative(rho, a, adag) * purity(rho) - purity_first_derivative(rho, a, adag)**2

### Random search

In [41]:
RNG = np.random.default_rng(seed=12345)

def random_rho(shape=(), nmax=NMAX, rng=RNG):
    x = 2 * rng.random((*shape, nmax + 1, nmax + 1)) - 1 + 1j * (2 * rng.random((*shape, nmax + 1, nmax + 1)) - 1)
    y = np.swapaxes(np.conj(x), -1, -2) @ x
    return y / (np.trace(y, axis1=-1, axis2=-2)[:, None, None])

random_rhos = random_rho((10000,))
np.min(np.real(objective(random_rhos)))

np.float64(0.1613131043126898)

### Minimization

In [ ]:
def objective_cholesky(xvec, a=A, adag=ADAG):
    x = xvec.view(np.complex128).reshape(a.shape)
    rho = np.conj(x).T @ x / np.sum(np.conj(x) * x)
    return np.real(objective(rho, a, adag))

# Construct an initial matrix X supported primarily on Fock states |1> and |2>
x_init_mat = np.zeros((NMAX + 1, NMAX + 1), dtype=np.complex128)
x_init_mat[1, 1] = 1.0
x_init_mat[2, 2] = 0.5  # Yields an initial mixture near the failure threshold

# Add small numerical perturbation to ensure non-zero gradient for all parameters
rng = np.random.default_rng(seed=42)
x_init_mat += 1e-4 * (rng.standard_normal(x_init_mat.shape) + 1j * rng.standard_normal(x_init_mat.shape))

x0_fock = x_init_mat.view(np.float64).flatten()

minimize(objective_cholesky, x0_fock)

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: -0.09599999999967657
        x: [ 7.195e-08 -2.355e-07 ...  4.999e-01 -9.586e-05]
      nit: 4
      jac: [ 4.917e-07 -1.237e-06 ... -3.353e-07  2.235e-08]
 hess_inv: [[ 9.701e-01  8.328e-02 ... -9.785e-02 -1.588e-05]
            [ 8.328e-02  7.677e-01 ...  2.723e-01  4.364e-05]
            ...
            [-9.785e-02  2.723e-01 ...  5.577e-01 -1.366e-04]
            [-1.588e-05  4.364e-05 ... -1.366e-04  1.000e+00]]
     nfev: 171
     njev: 9

In [43]:
basinhopping(objective_cholesky, x0_fock)

                    message: ['requested number of basinhopping iterations completed successfully']
                    success: True
                        fun: -0.09599999999967657
                          x: [ 7.195e-08 -2.355e-07 ...  4.999e-01
                              -9.586e-05]
                        nit: 100
      minimization_failures: 0
                       nfev: 41667
                       njev: 2193
 lowest_optimization_result:  message: Optimization terminated successfully.
                              success: True
                               status: 0
                                  fun: -0.09599999999967657
                                    x: [ 7.195e-08 -2.355e-07 ...
                                         4.999e-01 -9.586e-05]
                                  nit: 4
                                  jac: [ 4.917e-07 -1.237e-06 ...
                                        -3.353e-07  2.235e-08]
                             hess_inv: [[ 9.701e-01  

In [45]:
# Counter-example state construction: rho = p |1><1| + (1-p) |2><2|
p_val = 0.8  # Population within the failure domain p > (1 + sqrt(6))/5 ≈ 0.6899

rho_counter = np.zeros((NMAX + 1, NMAX + 1), dtype=np.complex128)
rho_counter[1, 1] = p_val
rho_counter[2, 2] = 1.0 - p_val

# Direct evaluation through their objective function
purity_val = purity(rho_counter)
first_deriv = purity_first_derivative(rho_counter)
second_deriv = purity_second_derivative(rho_counter)
obj_val = np.real(objective(rho_counter))

print(f"Purity P:                {np.real(purity_val):.6f}")
print(f"First derivative P':     {np.real(first_deriv):.6f}")
print(f"Second derivative P'':   {np.real(second_deriv):.6f}")
print(f"Objective (P*P'' - P'^2): {obj_val:.6f}")

Purity P:                0.680000
First derivative P':     0.800000
Second derivative P'':   0.800000
Objective (P*P'' - P'^2): -0.096000
